name: Go

on:
  push:
    branches: [v3]
  pull_request:
    branches: [v3]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x, 1.17.x]

    steps:
      - name: Start Redis v${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-port: 6379

      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test
